properties([
    parameters([
        string(name: 'TARGET_BRANCH', defaultValue: 'main', description: 'Which branch to build/deploy')
    ])
])

pipeline {
    agent {
        kubernetes {
            label 'dind-agent'
            defaultContainer 'docker'
            yamlFile 'jenkins/worker-template.yaml'
        }
    }
    environment {
        KUBECONFIG_CONTENT = credentials('jenkins-kubeconfig-base64')
        GIT_USER = 'mesutdmrz'
        GIT_EMAIL = 'mesutdmrz@gmail.com'
        DOCKER_USER = credentials('DOCKER_USER')
        DOCKER_PASS = credentials('DOCKER_PASS')
    }
    stages {
        stage('Deploy with Makefile') {
            steps {
                container('docker') {
                    script {
                        sh '''
                        mkdir -p /tmp/kube
                        echo "$KUBECONFIG_CONTENT" | base64 -d > /tmp/kube/config
                        export KUBECONFIG=/tmp/kube/config
                        '''
                        
                        // Parametreye göre ENV seçimi
                        def envValue = params.TARGET_BRANCH == 'main' ? 'prod' : 'test'
                        echo "Selected ENV: ${envValue}"
                        sh "kubectl get pods"
                        sh "ls"
                        sh 'git config --global --add safe.directory $WORKSPACE'
                        sh """
                        echo "${env.DOCKER_PASS}" | docker login -u "${env.DOCKER_USER}" --password-stdin
                        cd app
                        ls
                        make deploy ENV=${envValue}
                        """
                        withCredentials([string(credentialsId: 'git-token', variable: 'GIT_TOKEN')]) {
                            sh """
                            git config user.name "${GIT_USER}"
                            git config user.email "${GIT_EMAIL}"
                            git checkout ${params.TARGET_BRANCH}
                            git add k8s/overlays/${envValue}/kustomization.yaml
                            git commit -m "Update kustomize generated by Jenkins" || true
                            git push -f https://${GIT_TOKEN}@github.com/mesutdmrz/jenkins-test.git ${params.TARGET_BRANCH}
                            """
                        }
                    }
                }
            }
        }
    }
}
