properties([
    parameters([
        string(name: 'TARGET_BRANCH', defaultValue: 'main', description: 'Which branch to build/deploy')
    ])
])

pipeline {
    agent {
        kubernetes {
            label 'dind-agent'
            defaultContainer 'docker'
            yamlFile 'jenkins/worker-template.yaml'
        }
    }
    environment {
        KUBECONFIG_CONTENT = credentials('jenkins-kubeconfig-base64')
        GIT_USER = 'mesutdmrz'
        GIT_EMAIL = 'mesutdmrz@gmail.com'
        DOCKER_USER = credentials('DOCKER_USER')
        DOCKER_PASS = credentials('DOCKER_PASS')
    }
    stages {
        stage('Checkout & Prepare Workspace') {
            steps {
                container('docker') {
                    dir("$WORKSPACE") {
                        // Repo'yu checkout et
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: "${params.TARGET_BRANCH}"]],
                            userRemoteConfigs: [[
                                url: 'https://github.com/mesutdmrz/jenkins-test.git',
                                credentialsId: 'git-token'
                            ]]
                        ])
                        
                        // Git config
                        sh 'git config user.name "${GIT_USER}"'
                        sh 'git config user.email "${GIT_EMAIL}"'
                        
                        // Workspace temizle ve branch güncelle
                        sh 'git reset --hard'
                        sh 'git clean -fd'
                        sh "git fetch origin ${params.TARGET_BRANCH}"
                        sh "git checkout -B ${params.TARGET_BRANCH} origin/${params.TARGET_BRANCH}"
                    }
                }
            }
        }
        stage('Deploy with Makefile') {
            steps {
                container('docker') {
                    dir("$WORKSPACE") {
                        sh '''
                        mkdir -p /tmp/kube
                        echo "$KUBECONFIG_CONTENT" | base64 -d > /tmp/kube/config
                        export KUBECONFIG=/tmp/kube/config
                        '''
                        
                        // Parametreye göre ENV seçimi
                        def envValue = params.TARGET_BRANCH == 'main' ? 'prod' : 'test'
                        echo "Selected ENV: ${envValue}"
                        sh "kubectl get pods"
                        sh "ls"
                        
                        // Docker login ve deploy
                        sh """
                        echo "${env.DOCKER_PASS}" | docker login -u "${env.DOCKER_USER}" --password-stdin
                        cd app
                        ls
                        make deploy ENV=${envValue}
                        """
                        
                        // Kustomization push
                        withCredentials([string(credentialsId: 'git-token', variable: 'GIT_TOKEN')]) {
                            sh """
                            git add k8s/overlays/${envValue}/kustomization.yaml
                            git commit -m "Update kustomize generated by Jenkins" || true
                            git push -f https://${GIT_TOKEN}@github.com/mesutdmrz/jenkins-test.git ${params.TARGET_BRANCH}
                            """
                        }
                    }
                }
            }
        }
    }
}
