apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watcher
spec:
  template:
    spec:
      containers:
        - name: pod-watcher
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: common-config-volume
              mountPath: /etc/pod-watcher/common
              readOnly: true
            - name: profile-config-volume
              mountPath: /etc/pod-watcher/profile
              readOnly: true
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config
        - name: profile-config-volume
          configMap:
            name: pod-watcher-prod-profile-config
