apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: dind
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.11.2-4-jre11
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    - name: docker
      image: docker:dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
