apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-dind
spec:
  containers:
  - name: docker
    image: mesut4730/customjenkinsagent:v2
    securityContext:
      privileged: true
    command:
    - dockerd-entrypoint.sh
    args:
    - --host=tcp://0.0.0.0:2375
    - --host=unix:///var/run/docker.sock
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
  volumes:
  - name: docker-graph-storage
    emptyDir: {}
